//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALPHA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogin
    {
        public string userName { get; set; }
        public string pwd { get; set; }
        public int idPerson { get; set; }
    
        public virtual tblPerson tblPerson { get; set; }
    }
}
